<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Hydrator\Controller;

use MSBios\Application\Controller\IndexController as DefaultIndexController;
use MSBios\Hydrator\HydratorManagerAwareInterface;
use MSBios\Hydrator\HydratorManagerAwareTrait;

/**
 * Class IndexController
 * @package MSBios\Hydrator\Controller
 */
class IndexController extends DefaultIndexController implements HydratorManagerAwareInterface
{
    use HydratorManagerAwareTrait;

    /**
     * @return \Zend\View\Model\ViewModel
     */
    public function indexAction()
    {
        r($this->getHydratorManager());
        die();
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}
